# Generated by Django 3.0.7 on 2020-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='altitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='longtitude',
            field=models.FloatField(),
        ),
    ]
