# Generated by Django 3.0.7 on 2020-06-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200630_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
