# Generated by Django 3.0.7 on 2020-06-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200630_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
